#!/bin/bash
# ============================================
# Recon Report Builder (Markdown Publisher)
# Converts latest recon results into a GitHub-ready report
# ============================================

set -e
REPORT_DIR="reports"
OUTPUT_FILE="${REPORT_DIR}/latest.md"
SCAN_DIR="$HOME/recon/output"

mkdir -p "$REPORT_DIR"

{
  echo "# 🧩 Recon Summary Report"
  echo
  echo "**Generated:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
  echo
  echo "## Active Targets"
  echo
  find "$SCAN_DIR" -type f -name '*live_fixed.txt' | while read -r file; do
    base=$(basename "$file")
    echo "### $base"
    echo
    echo '```'
    head -n 20 "$file" || echo "(no data)"
    echo '```'
    echo
  done
  echo "---"
  echo "_Automated report generated by Recon Automation Stack_"
} > "$OUTPUT_FILE"

echo "[INFO] Markdown report created at $OUTPUT_FILE"
