#!/bin/bash
# Quick Manual IDOR Test Guide
# This script provides step-by-step instructions for manual IDOR testing

echo "============================================================"
echo "IDOR Testing - Manual Method"
echo "============================================================"
echo ""
echo "The API endpoints are failing because Rapyd uses:"
echo "  - Signature-based API authentication (not Bearer tokens)"
echo "  - Dashboard frontend uses session cookies (not API tokens)"
echo ""
echo "For IDOR testing, you need to test the DASHBOARD, not the API."
echo ""
echo "============================================================"
echo "STEP 1: Get Payment ID from Dashboard"
echo "============================================================"
echo ""
echo "1. Log into Account B:"
echo "   https://dashboard.rapyd.net"
echo ""
echo "2. Navigate to: Collect → Payments"
echo "   Or: https://dashboard.rapyd.net/collect/payments/list"
echo ""
echo "3. Get Payment ID:"
echo "   - Create a new payment OR"
echo "   - Click on existing payment"
echo "   - Copy payment ID from URL:"
echo "     https://dashboard.rapyd.net/collect/payments/<PAYMENT_ID>"
echo ""
read -p "Press Enter when you have the payment ID..."
echo ""
echo "Enter the Payment ID:"
read -p "PAYMENT_ID: " PAYMENT_ID
echo ""
echo "============================================================"
echo "STEP 2: Test IDOR Vulnerability"
echo "============================================================"
echo ""
echo "Testing URL: https://dashboard.rapyd.net/collect/payments/$PAYMENT_ID"
echo ""
echo "Test Steps:"
echo "1. Log into Account B → Navigate to payment → Should work ✅"
echo "2. Log OUT of Account B"
echo "3. Log into Account A (different account)"
echo "4. Navigate to: https://dashboard.rapyd.net/collect/payments/$PAYMENT_ID"
echo "5. Check if Account A can see Account B's payment"
echo ""
echo "============================================================"
echo "Expected Results:"
echo "============================================================"
echo ""
echo "✅ IDOR Vulnerability Found:"
echo "   - Account A can see Account B's payment"
echo "   - Payment details visible to unauthorized user"
echo "   - Take screenshot as evidence!"
echo ""
echo "❌ No Vulnerability:"
echo "   - Account A gets 'Access Denied' or 404"
echo "   - Authorization is working correctly"
echo ""
echo "============================================================"
echo "Evidence Collection:"
echo "============================================================"
echo ""
echo "If IDOR found, capture:"
echo "1. Screenshot showing Account A logged in"
echo "2. Screenshot showing Account B's payment details"
echo "3. URL bar showing the payment ID"
echo "4. Network request from DevTools (F12 → Network)"
echo ""
echo "Open browser now? (y/n)"
read -p "Open dashboard.rapyd.net? [y/N]: " OPEN_BROWSER
if [[ "$OPEN_BROWSER" =~ ^[Yy]$ ]]; then
    echo ""
    echo "Opening browser..."
    # Try to open browser (works on most systems)
    if command -v xdg-open &> /dev/null; then
        xdg-open "https://dashboard.rapyd.net/collect/payments/$PAYMENT_ID"
    elif command -v open &> /dev/null; then
        open "https://dashboard.rapyd.net/collect/payments/$PAYMENT_ID"
    else
        echo "Please manually open: https://dashboard.rapyd.net/collect/payments/$PAYMENT_ID"
    fi
fi
echo ""
echo "============================================================"
echo "Test Complete!"
echo "============================================================"
echo ""
echo "Next steps:"
echo "1. Document findings"
echo "2. Take screenshots"
echo "3. Submit to Bugcrowd"
echo ""
echo "See MANUAL_IDOR_TESTING.md for detailed guide"

