#!/bin/bash
# Vulnerability Hunter Agent (Nuclei)
# Performs Nuclei scans on discovered endpoints
# Input: ~/recon-stack/output/http.json
# Output: ~/recon-stack/output/nuclei-findings.json

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT_DIR="$REPO_ROOT/output"
HTTP_FILE="$OUTPUT_DIR/http.json"
NUCLEI_OUTPUT="$OUTPUT_DIR/nuclei-findings.json"
NUCLEI_TEMPLATES_DIR="$REPO_ROOT/nuclei-templates"

# Ensure output directory exists
mkdir -p "$OUTPUT_DIR"

# Log file
LOG_FILE="$OUTPUT_DIR/recon-run.log"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"
}

log "=== Vulnerability Hunter Agent (Nuclei) Starting ==="

# Check if nuclei is installed
command -v nuclei >/dev/null 2>&1 || { log "ERROR: nuclei not installed"; exit 1; }
command -v jq >/dev/null 2>&1 || { log "ERROR: jq not installed"; exit 1; }

# Check if http.json exists
if [ ! -f "$HTTP_FILE" ]; then
    log "ERROR: http.json not found at $HTTP_FILE"
    log "Please run web mapper agent first (scripts/run_httpx.sh)"
    exit 1
fi

# Extract URLs from http.json
TEMP_URLS="$OUTPUT_DIR/temp_urls.txt"
jq -r '.[] | select(.url != null) | .url' "$HTTP_FILE" > "$TEMP_URLS" 2>/dev/null || touch "$TEMP_URLS"

# Check if we have URLs
if [ ! -s "$TEMP_URLS" ]; then
    log "WARNING: No URLs found in http.json"
    echo "[]" > "$NUCLEI_OUTPUT"
    rm -f "$TEMP_URLS"
    exit 0
fi

URL_COUNT=$(wc -l < "$TEMP_URLS")
log "Scanning $URL_COUNT endpoints with Nuclei..."

# Configuration
RATE_LIMIT="${NUCLEI_RATE_LIMIT:-50}"
BULK_SIZE="${NUCLEI_BULK_SIZE:-25}"
TIMEOUT="${NUCLEI_TIMEOUT:-10}"

# Update Nuclei templates first (non-blocking)
log "Updating Nuclei templates (background)..."
nuclei -update-templates -silent 2>&1 | tee -a "$LOG_FILE" || {
    log "WARNING: Template update failed (continuing with existing templates)"
}

# Build nuclei command
NUCLEI_CMD="nuclei -l \"$TEMP_URLS\" -json -o \"$NUCLEI_OUTPUT\""

# Add custom templates if directory exists and has templates
if [ -d "$NUCLEI_TEMPLATES_DIR" ] && [ "$(find "$NUCLEI_TEMPLATES_DIR" -type f -name '*.yaml' -o -name '*.yml' 2>/dev/null | wc -l)" -gt 0 ]; then
    TEMPLATE_COUNT=$(find "$NUCLEI_TEMPLATES_DIR" -type f \( -name '*.yaml' -o -name '*.yml' \) 2>/dev/null | wc -l)
    log "Including $TEMPLATE_COUNT custom templates from $NUCLEI_TEMPLATES_DIR"
    NUCLEI_CMD="$NUCLEI_CMD -t \"$NUCLEI_TEMPLATES_DIR\""
fi

# Comprehensive bug bounty attack surface
# Scan all templates except truly problematic categories
# This provides maximum coverage for bug bounty hunting

# Exclusion list: Only exclude categories that could cause harm or are too aggressive
# Exclude: dos, fuzzing (can be too aggressive), malware, intrusive, network scans
EXCLUDE_TAGS="${NUCLEI_EXCLUDE_TAGS:-dos,fuzzing,malware,intrusive,network}"

# Build command with comprehensive safety flags
# Severity: Scan all severity levels for maximum coverage
NUCLEI_CMD="$NUCLEI_CMD \
    -rate-limit $RATE_LIMIT \
    -bulk-size $BULK_SIZE \
    -timeout $TIMEOUT \
    -retries 1 \
    -severity info,low,medium,high,critical \
    -exclude-tags $EXCLUDE_TAGS \
    -no-color \
    -silent"

# Optional: Focus on specific high-value categories if NUCLEI_FOCUS_TAGS is set
# If unset, scans all templates (except excluded)
if [ -n "${NUCLEI_FOCUS_TAGS:-}" ]; then
    log "Focusing on specific categories: ${NUCLEI_FOCUS_TAGS}"
    NUCLEI_CMD="$NUCLEI_CMD -tags ${NUCLEI_FOCUS_TAGS}"
else
    log "Running comprehensive scan across all bug bounty categories"
fi

# Run nuclei with timeout
log "Running Nuclei scan (this may take a while)..."
TIMEOUT_VAL="${NUCLEI_SCAN_TIMEOUT:-3600}"  # 1 hour default
timeout "$TIMEOUT_VAL" bash -c "$NUCLEI_CMD" 2>&1 | tee -a "$LOG_FILE" || {
    EXIT_CODE=$?
    if [ $EXIT_CODE -eq 124 ]; then
        log "WARNING: Nuclei scan timed out after ${TIMEOUT_VAL}s (checking for partial output)"
    else
        log "WARNING: Nuclei encountered errors (exit code: $EXIT_CODE, checking for partial output)"
    fi
}

# Check if output file was created, if not create empty array
NUCLEI_TEMP="$NUCLEI_OUTPUT.tmp"
if [ ! -f "$NUCLEI_OUTPUT" ] || [ ! -s "$NUCLEI_OUTPUT" ]; then
    log "No findings generated by Nuclei"
    echo "[]" > "$NUCLEI_OUTPUT"
else
    # Nuclei outputs NDJSON (newline-delimited JSON), convert to array
    log "Processing Nuclei output (NDJSON to JSON array)..."
    
    # Check if it's already a valid JSON array
    if jq -e 'type == "array"' "$NUCLEI_OUTPUT" >/dev/null 2>&1; then
        log "Output is already a JSON array"
        FINDINGS_COUNT=$(jq 'length' "$NUCLEI_OUTPUT" 2>/dev/null || echo "0")
    else
        # Convert NDJSON to JSON array
        if jq -s '.' "$NUCLEI_OUTPUT" > "$NUCLEI_TEMP" 2>/dev/null; then
            mv "$NUCLEI_TEMP" "$NUCLEI_OUTPUT"
            FINDINGS_COUNT=$(jq 'length' "$NUCLEI_OUTPUT" 2>/dev/null || echo "0")
        else
            log "WARNING: Failed to parse Nuclei output, creating empty array"
            echo "[]" > "$NUCLEI_OUTPUT"
            FINDINGS_COUNT=0
        fi
    fi
    
    if [ "$FINDINGS_COUNT" -gt 0 ]; then
        # Extract severity breakdown
        CRITICAL=$(jq '[.[] | select(.info.severity == "critical")] | length' "$NUCLEI_OUTPUT" 2>/dev/null || echo "0")
        HIGH=$(jq '[.[] | select(.info.severity == "high")] | length' "$NUCLEI_OUTPUT" 2>/dev/null || echo "0")
        MEDIUM=$(jq '[.[] | select(.info.severity == "medium")] | length' "$NUCLEI_OUTPUT" 2>/dev/null || echo "0")
        LOW=$(jq '[.[] | select(.info.severity == "low")] | length' "$NUCLEI_OUTPUT" 2>/dev/null || echo "0")
        INFO=$(jq '[.[] | select(.info.severity == "info")] | length' "$NUCLEI_OUTPUT" 2>/dev/null || echo "0")
        
        log "Found $FINDINGS_COUNT vulnerabilities:"
        log "  - Critical: $CRITICAL"
        log "  - High: $HIGH"
        log "  - Medium: $MEDIUM"
        log "  - Low: $LOW"
        log "  - Info: $INFO"
    else
        log "No vulnerabilities found"
    fi
fi

# Cleanup
rm -f "$TEMP_URLS" "$NUCLEI_TEMP"

log "=== Vulnerability Hunter Agent Complete ==="
log "Output: $NUCLEI_OUTPUT"

