#!/usr/bin/env python3
"""
Legal & Scope Verification Guide
Verify what's legal and in-scope BEFORE testing
"""

import json
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent

def scope_verification_guide():
    """Guide for verifying legal scope"""
    
    print("=" * 60)
    print("LEGAL & SCOPE VERIFICATION GUIDE")
    print("=" * 60)
    print()
    print("⚠️  CRITICAL: Verify scope BEFORE testing!")
    print("   Testing out of scope = Illegal and can result in:")
    print("   - Criminal charges")
    print("   - Lawsuits")
    print("   - Ban from bug bounty platforms")
    print()
    
    print("=" * 60)
    print("WHAT IS LEGAL & IN SCOPE")
    print("=" * 60)
    print()
    
    print("✅ RAPYD - CONFIRMED IN SCOPE")
    print("   Program: https://bugcrowd.com/engagements/rapyd")
    print("   ✅ LEGAL: Yes (public bug bounty program)")
    print("   ✅ IN SCOPE:")
    print("      - sandboxapi.rapyd.net/v1")
    print("      - dashboard.rapyd.net")
    print("      - verify.rapyd.net")
    print("      - checkout.rapyd.net")
    print("   ✅ ALLOWED:")
    print("      - Manual API testing")
    print("      - Sandbox testing")
    print("      - Dashboard testing")
    print("   ❌ PROHIBITED:")
    print("      - Automation on forms")
    print("      - Rate limit abuse")
    print("   📋 REQUIRED:")
    print("      - X-Bugcrowd header with your username")
    print("      - Use @bugcrowdninja.com email")
    print()
    
    print("✅ MASTERCARD - CONFIRMED IN SCOPE")
    print("   Program: https://bugcrowd.com/engagements/mastercard")
    print("   ✅ LEGAL: Yes (public bug bounty program)")
    print("   ✅ IN SCOPE:")
    print("      - developer.mastercard.com")
    print("      - api.mastercard.com")
    print("      - masterpassteststore.com (test store)")
    print("      - Finicity APIs")
    print("   ✅ ALLOWED:")
    print("      - API testing")
    print("      - Test store testing")
    print("   ⚠️  PARTIAL SAFE HARBOR:")
    print("      - Review program rules for restrictions")
    print()
    
    print("=" * 60)
    print("WHAT IS RISKY / OUT OF SCOPE")
    print("=" * 60)
    print()
    
    print("❌ APPLE CDN ENDPOINTS - LIKELY OUT OF SCOPE")
    print("   ❌ LEGAL RISK: Testing without verification")
    print("   ❌ OUT OF SCOPE:")
    print("      - 2b4a6b31ca2273bb.apple.com (CDN subdomain)")
    print("      - d425438857f7719a.apple.com (CDN subdomain)")
    print("   ⚠️  WHY:")
    print("      - Hash prefix = CDN/cache endpoint")
    print("      - CDN endpoints usually OUT OF SCOPE")
    print("      - Not real Apple APIs")
    print("   ✅ HOW TO VERIFY:")
    print("      1. Check Apple's bug bounty scope:")
    print("         https://bugcrowd.com/apple")
    print("      2. Look for explicit CDN subdomain inclusion")
    print("      3. If not listed, DO NOT TEST")
    print()
    
    print("❌ PAYPAL CDN ENDPOINTS - LIKELY OUT OF SCOPE")
    print("   ❌ LEGAL RISK: Testing without verification")
    print("   ❌ OUT OF SCOPE:")
    print("      - 0cd20b6fe61233e4a24bf70f30c9ba46.paypal.com")
    print("      - 16695532.paypal.com")
    print("   ⚠️  WHY:")
    print("      - Hash prefix = CDN subdomain")
    print("      - CDN endpoints usually OUT OF SCOPE")
    print("      - PayPal may not even have public bug bounty")
    print("   ✅ HOW TO VERIFY:")
    print("      1. Check if PayPal has bug bounty:")
    print("         https://bugcrowd.com/paypal")
    print("         https://hackerone.com/paypal")
    print("      2. If no program exists, DO NOT TEST")
    print("      3. If program exists, verify scope")
    print()
    
    print("⚠️  ATLASSIAN - NEED VERIFICATION")
    print("   ⚠️  LEGAL RISK: Unknown until verified")
    print("   ⚠️  STATUS:")
    print("      - Listed in targets.txt")
    print("      - Program: https://bugcrowd.com/atlassian")
    print("      - BUT: No endpoints discovered yet")
    print("   ✅ HOW TO VERIFY:")
    print("      1. Check program scope:")
    print("         https://bugcrowd.com/atlassian")
    print("      2. Verify api.atlassian.com is in scope")
    print("      3. Check for authentication requirements")
    print("      4. Only test EXPLICITLY listed domains")
    print()
    
    print("⚠️  KRAKEN - NEED VERIFICATION")
    print("   ⚠️  LEGAL RISK: Unknown until verified")
    print("   ⚠️  STATUS:")
    print("      - Listed in targets.txt")
    print("      - Program: https://hackerone.com/kraken")
    print("      - BUT: No endpoints discovered yet")
    print("   ✅ HOW TO VERIFY:")
    print("      1. Check program scope:")
    print("         https://hackerone.com/kraken")
    print("      2. Verify api.kraken.com is in scope")
    print("      3. Check for authentication requirements")
    print("      4. Review out-of-scope items carefully")
    print()
    
    print("=" * 60)
    print("HOW TO VERIFY SCOPE (STEP-BY-STEP)")
    print("=" * 60)
    print()
    print("STEP 1: Find the official bug bounty program")
    print("   - Bugcrowd: https://bugcrowd.com/[program-name]")
    print("   - HackerOne: https://hackerone.com/[program-name]")
    print("   - Look for 'Program Brief' or 'Scope' section")
    print()
    
    print("STEP 2: Read the scope section carefully")
    print("   - Look for 'In-Scope' or 'Scope' section")
    print("   - Check for explicit domain/subdomain lists")
    print("   - Note any restrictions or requirements")
    print()
    
    print("STEP 3: Check out-of-scope items")
    print("   - Look for 'Out-of-Scope' section")
    print("   - CDN endpoints often listed here")
    print("   - Third-party services often excluded")
    print()
    
    print("STEP 4: Verify your target is explicitly listed")
    print("   - If domain NOT explicitly listed = OUT OF SCOPE")
    print("   - When in doubt, ask program team")
    print("   - Better safe than sorry")
    print()
    
    print("=" * 60)
    print("CURRENT STATUS - WHAT YOU CAN TEST NOW")
    print("=" * 60)
    print()
    
    print("✅ SAFE TO TEST RIGHT NOW:")
    print("   1. Rapyd - sandboxapi.rapyd.net/v1")
    print("      - Confirmed in scope")
    print("      - You have API keys")
    print("      - Safe harbor protection")
    print()
    print("   2. Mastercard - developer.mastercard.com")
    print("      - Confirmed in scope")
    print("      - Public program")
    print("      - Partial safe harbor")
    print()
    
    print("❌ DO NOT TEST (Need verification first):")
    print("   1. Apple CDN endpoints")
    print("      - Likely out of scope")
    print("      - CDN subdomains")
    print()
    print("   2. PayPal CDN endpoints")
    print("      - Likely out of scope")
    print("      - Need to verify program exists")
    print()
    
    print("=" * 60)
    print("RECOMMENDATION")
    print("=" * 60)
    print()
    print("🎯 FOCUS ON RAPYD (100% SAFE)")
    print()
    print("Why Rapyd:")
    print("   ✅ Confirmed in scope")
    print("   ✅ You have access")
    print("   ✅ Safe harbor protection")
    print("   ✅ Clear testing guidelines")
    print("   ✅ High rewards ($1,500-$4,500)")
    print()
    print("Next steps:")
    print("   1. Test Rapyd endpoints ONLY")
    print("   2. Follow Rapyd's rules exactly")
    print("   3. Use X-Bugcrowd header")
    print("   4. Test sandbox only")
    print("   5. Manual testing only")
    print()
    
    print("=" * 60)
    print("LEGAL PROTECTION")
    print("=" * 60)
    print()
    print("Safe Harbor Protection:")
    print("   ✅ Rapyd: Full safe harbor")
    print("   ⚠️  Mastercard: Partial safe harbor")
    print("   ❌ Out-of-scope testing: NO protection")
    print()
    print("What safe harbor means:")
    print("   - You won't face legal action")
    print("   - Company won't sue you")
    print("   - Protected if you follow rules")
    print()
    print("⚠️  IMPORTANT:")
    print("   - Safe harbor ONLY applies to in-scope testing")
    print("   - Out-of-scope = NO protection")
    print("   - Always verify scope first")
    print()
    
    print("=" * 60)

if __name__ == "__main__":
    scope_verification_guide()


